# Generated by Django 3.0.3 on 2020-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutrtionFactsLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=50)),
                ('serving_size', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
            ],
        ),
    ]
