# Generated by Django 3.0.3 on 2020-07-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20200714_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutrtionFactsLabel',
            new_name='NutritionFactsLabel',
        ),
    ]
